/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TelasPousada;

import DalPousada.ConexaoPousada;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author CT Desenvolvimento
 */
public class Relatorio extends javax.swing.JFrame {

    Connection conexao =  ConexaoPousada.conector();
    PreparedStatement pst = null;
    ResultSet rs = null; 
    public Relatorio() {
        initComponents();
    }
    
    String datas;
       int ano;
       int mes;
    
     private void Relatorio(){
       
      String sql = "SELECT COUNT(*) AS total_reservas FROM tbl_quartos WHERE MONTH(DataSaida) = ? AND YEAR(DataSaida) = ? ";
    
       datas = DatasRe.getText();
       mes = Integer.parseInt(datas.substring(0, 2));
       ano = Integer.parseInt(datas.substring(3, 7));
         System.out.println(mes);
         System.out.println(ano);
       
    try{
    pst = conexao.prepareStatement(sql);
    pst.setInt(1, mes);
     pst.setInt(2, ano);
    rs = pst.executeQuery();
    if (rs.next()){
        int total = rs.getInt("total_reservas");
        Reservas.setText(String.valueOf(total));
        Lucro();
    } else{
        JOptionPane.showMessageDialog(null, "Deu erro!");
        //As linhas abaixo limpam os campos do formulário
    
    } 
       }
   catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
            }

    }

     
     private void Lucro(){
         
     String sql = "SELECT SUM(total) AS totalPrint FROM tbl_quartos WHERE MONTH(dataReserva) = ? AND YEAR(dataReserva) = ?";
      try{
     pst = conexao.prepareStatement(sql);
     pst.setInt(1, mes);
     pst.setInt(2, ano);
    rs = pst.executeQuery();
    if (rs.next()){
        int total = rs.getInt("totalPrint");
        Lucro.setText(String.valueOf(total));
        RelatorioCanceladas();
    } else{
        JOptionPane.showMessageDialog(null, "Deu erro!");
        //As linhas abaixo limpam os campos do formulário
    
    } 
       }
   catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
            }

    }

     private void RelatorioCanceladas(){
       
      String sql = "SELECT COUNT(*) AS total_canceladas FROM tbl_veri WHERE MONTH(saida) = ? AND YEAR(saida) = ? ";
         System.out.println(mes);
         System.out.println(ano);
      
    try{
    pst = conexao.prepareStatement(sql);
    pst.setInt(1, mes);
    pst.setInt(2, ano);
    rs = pst.executeQuery();
    if (rs.next()){
        int total = rs.getInt("total_canceladas");
        Canceladas.setText(String.valueOf(total));
    } else{
        JOptionPane.showMessageDialog(null, "Deu erro!");
        //As linhas abaixo limpam os campos do formulário
    
    } 
       }
   catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
            }

    }
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DatasRe = new javax.swing.JFormattedTextField();
        Lucro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Reservas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Canceladas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        try {
            DatasRe.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        DatasRe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatasReActionPerformed(evt);
            }
        });
        DatasRe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DatasReKeyPressed(evt);
            }
        });

        jLabel1.setText("Lucro");

        jLabel2.setText("Reservas");

        jLabel3.setText("Digite a data desejada");

        jLabel4.setText("Canceladas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(DatasRe, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lucro, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Reservas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(Canceladas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DatasRe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Reservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(Lucro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Canceladas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DatasReActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatasReActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DatasReActionPerformed

    private void DatasReKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DatasReKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            Relatorio();
        };
        // TODO add your handling code here:
    }//GEN-LAST:event_DatasReKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Canceladas;
    private javax.swing.JFormattedTextField DatasRe;
    private javax.swing.JTextField Lucro;
    public static javax.swing.JTextField Reservas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
